name: CI/CD for Production Branch [Jsonrock]

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: jsonrock

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Add Backend Envrionemnt Variables
        run: cp /home/ankit/projects/jsonrock/.env.backend apps/server/.env

      - name: Add Frontend Envrionemnt Variables
        run: cp /home/ankit/projects/jsonrock/.env.frontend apps/web/.env

      - name: Install Dependencies
        run: pnpm install

      - name: Build Application 
        run: pnpm build

      - name: Restart Backend Application with PM2
        run: pm2 restart be-jsonrock

      - name: Restart Frontend Application with PM2
        run: pm2 restart fe-jsonrock